apiVersion: 1

datasources:
  - name: CTT Dashboard API
    type: marcusolsson-json-datasource
    access: proxy
    url: http://ctt-dashboard:5001/api/v1
    isDefault: true
    editable: true
    jsonData:
      queryParams: ""
    secureJsonData:
      httpHeaderValue1: "application/json"
